#!/usr/bin/env python3
# This code is licensed under GNU General Public License v3.0. I encouruage you to do the same to the software you write!

# TODO: queee {1-10} this will play first to tenth episode |  queee {1 2 3} This will play first, second and third episode

try:
    from bs4 import BeautifulSoup
    import requests, subprocess, sys, random, time
    from termcolor import colored
    from prettytable import PrettyTable
    from urllib.error import HTTPError
    from halo import Halo
    
    from func import httperror_assess
    
except ImportError or ModuleNotFoundError:
    # Using python color codes instead of termcolor if it isn't found
    print("\033[1;31;40mOne or more library is missing! Check the list of libraries!")
    sys.exit()


episodes = []
counter = 0


# It fetches the episodes from this link, So that episode is not avaliable.
# Historically this used to be help wanted, but since it was the first episode it was changed to the last
try:
    link = "https://www.megacartoons.net/truth-or-square/"
    raw = requests.get(link).text
    soup = BeautifulSoup(raw, "html.parser")

except HTTPError as e:
    httperror_assess(e.code)    


for data in soup.find_all("a", class_ = "btn btn-sm btn-default"):
    counter += 1
    episodes.append(data.get("href"))
            
# spinner were not added as this function is always run, hence
# adding it would cause maybe a lot of errors and would be trivial
def ListEpisodes(limit_real):
    counter = 0
    table = PrettyTable()
    
    episode_number = []
    episode_title = []
    for data in soup.find_all("a", class_ = "btn btn-sm btn-default", limit = limit_real):        
        counter += 1
        episode_title.append(data.get("title"))
        episode_number.append(colored(counter, "cyan" ))
    
    table.add_column("Title", episode_title)
    table.add_column("Episode", episode_number)
    
    table.align["Title"] = "l"
    print(table)


# This function get the direct mp4 link
@Halo(text="Getting video source", spinner="shark", color="green")
def VideoSource(source):

    raw = requests.get(source).text
    soup = BeautifulSoup(raw, "html.parser")

    # This took me way to long to figure out, DONT TOUCH
    link = soup.find("input", {"name":"main_video_url"})["value"]
    return link

@Halo(text="Playing the episode", spinner="shark", color="green")
def Play(DirectLink):
    try:
        subprocess.run(["mpv", DirectLink],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.STDOUT)
    
    except subprocess.CalledProcessError:
        print(colored("\nAn error occured while tying to play the video! Make sure you have mpv or youtube-dl installed.", "red"))
    
    except KeyboardInterrupt:
        print(colored("\nUser interruped with the operation, aborting.", "red"))
        sys.exit()


@Halo(text="Downloading the episode", spinner="shark", color="green")
def Download(source):
    try:
        subprocess.run(["youtube-dl", source], 
            stdout=subprocess.DEVNULL,
            stderr=subprocess.STDOUT)
        print(colored("\nDownload complete!", "green"))
    
    except ImportError or subprocess.CalledProcessError:
        print(colored("Downloading the video failed. Be sure to have youtube-dl installed.", "red"))

    except KeyboardInterrupt:
        print(colored("\nUser interruped with the operation, aborting.", "red"))
        sys.exit()


try:
    args = sys.argv[1]
except IndexError:
    args = ''

try:
    args2 = sys.argv[2]
except:
    pass


# Download Function
try:
    if args.replace(' ', '') in ["--download", "-d"]:
        try:
            args2 = int(args2)
            print(f"Downloading episode {colored(args2, 'cyan')}")
            real = VideoSource(episodes[args2 - 1])
            Download(real)

        except IndexError or ValueError:
            print(colored("No arguments passed with download function or the index is out of range, aborting...!", "red"))

    # Dowload all
    elif args.replace(' ', '') in ["--download-all", "-da"]:
        dled = 0
        try:
            print(colored("Downloading all fetched episodes.", "green"))
            for x in range(len(episodes)):
                print(f"Downloading episode {colored(x+1, 'cyan')}")
                source = VideoSource(episodes[x+1])
                Download(source)
                print(f"Episode {x+1} downloaded!", end="")
                time.sleep(2)
                print("\r", end="")
                dled += 1
                continue
            
            print(colored(f"All {len(episodes)} are downloaded!", "green"))

        except HTTPError as e:
            httperror_assess(e.code)
            
        finally:
            print(colored(f"{dled} episodes were downloaded."))
           
    elif args.replace(' ', '') in ["--binge", "-b"]:
        try:
            print("Playing every episode from beggining")

            for x in range(len(episodes)):
                print(f"Playing episode {x + 1}", end = "")
                source = VideoSource(episodes[x + 1])
                Play(source)
                print(f"Playing episode {x + 1}", end = "")
                continue

        except HTTPError as e:
            httperror_assess(e.code)

    # List function
    elif args.replace(' ', '') in ["--list", "-l"]:
        try:
            args2 = int(args2)
            ListEpisodes(args2)

        except:
            ListEpisodes(339)

    # Play function
    elif args.replace(' ', '') in ["--play", "-p"]:
        try:
            args2 = int(args2)
            real = VideoSource(episodes[args2 - 1])
            Play(real)
        
        except ValueError or IndexError:
            print(colored("No arguments were passed with the play function or the index is out of range, aborting...", "red"))

    elif args.replace('  ', '') in ['--update', "-u"]:
        print(colored("This is higly experimental and only works if you have installed spongebob-cli with git clone command!", "red"))
        sys.subprocess(["git", "fetch"])

    elif args.replace('  ', '') in ["--random", "-r"]:
        real = VideoSource(episodes[round(random.uniform(1, 337))])
        Play(real)

    elif args.replace(' ', '') in ["--help", "-h"]:
        print("""
        --download | -d, usage --download {a number of a episode}, This will download that video under a directory the command was run
        --download-all | -da, usage --download-all, This will download every video spongebob video it scrapes
        --binge | -b , usage spongebob-cli --binge, This is used to start the first episode to the last
        --list | -l, usage --list, this will list all the episodes and then exit the programm
        --list | -l, usage --list {number} this will show the number of episodes with the limit you provided.
        --play | -p, usage --play {a number of a episode}, This will play the episode without listing the episodes
        --random | -r, usage spongebob-cli --random, This will play a random episode
        --help | -h, usage --help this will print what each argument does
        """)

    # This is if no arguments were passed.
    else:
        ListEpisodes(339)
        print(colored("No arguments were passed. Default settings applied.\n", "green"))

        while(True):
            try:
                video_input = input("What episode do you want to watch? (type a number by the right side): ").replace(' ', '')
                video_input = int(video_input)
                
            except ValueError or AttributeError:
                if video_input in ["exit", "quit", "close", 'q']:
                    print("Quitting the programm!")
                    sys.exit()

                print(colored("You need to type a number!", "red"))
                continue

            except IndexError:
                print("The video you chose is out of range or doesnt exist")
                continue
 
            real = VideoSource(episodes[video_input - 1])
            print(colored(f"Now playing: {real}\n", "green"))
            Play(real)
            
 

except KeyboardInterrupt:
    print(colored("\nUser interruped with the operation, aborting.", "red"))
    sys.exit()
